### ISSUE TITLE
Error about show-and-tell.pb file

### ISSUE THREAD

**Issue by shaunVB** [ColeMurray/medium-show-and-tell-caption-generator#4]
Hey thanks for sharing this great project.
Can you please help me with this error about show-and-tell.pb file

$ docker run -v $PWD:/opt/app -e PYTHONPATH=$PYTHONPATH:/opt/app -it colemurray/medium-show-and-tell-caption-generator  python3 /opt/app/medium_show_and_tell_caption_generator/inference.py --model_path /opt/app/etc/show-and-tell.pb --input_files /opt/app/imgs/trading_floor.jpg --vocab_file /opt/app/etc/word_counts.txt
Traceback (most recent call last):
  File "/opt/app/medium_show_and_tell_caption_generator/inference.py", line 58, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/opt/app/medium_show_and_tell_caption_generator/inference.py", line 30, in main
    model = ShowAndTellModel(FLAGS.model_path)
  File "/opt/app/medium_show_and_tell_caption_generator/model.py", line 12, in __init__
    self._load_model(model_path)
  File "/opt/app/medium_show_and_tell_caption_generator/model.py", line 30, in _load_model
    raise RuntimeError("Missing model file at path: {}".format(frozen_graph_path))
RuntimeError: Missing model file at path: /opt/app/etc/show-and-tell.pb

**Comment by thunfischtoast** [comment]
Can you check that the model was downloaded sucessfully? If you followed the Getting started steps the `show-and-tell.pb` file should be present in the folder which you see when executing `echo $PDW`.

**Comment by ColeMurray** [comment]
Closing due to inactivity.
